<a href="https://colab.research.google.com/github/IrynaBarnych/AI_lab2/blob/main/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Завдання 1
Створіть масив з елементами від 1 до 12. Виведіть розмір та тип масиву

In [ ]:
import numpy as np
arr = np.array(range(1, 13))

print("Розмір масиву:", arr.size)
print("Масив:", arr)

Розмір масиву: 12
Масив: [ 1  2  3  4  5  6  7  8  9 10 11 12]


Завдання №3
Створіть матрицю 8х8 з 0 та 1 розміщеними в шаховому порядку

In [ ]:
matrix = np.zeros((8, 8), dtype=int)

matrix[::2, ::2] = 0
matrix[1::2, 1::2] = 0
matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Завдання 4
Створіть випадкову матрицю 4х3. Знайдіть суму елементів в стовпчиках\рядках\усій матриці

In [ ]:
matrix = np.random.randint(0, 10, size=(4, 3))

print("Матриця:")
print(matrix)


Матриця:
[[5 7 1]
 [4 3 4]
 [8 4 8]
 [3 1 0]]
